// <auto-generated />
namespace Lexicon_LMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changeInEvent : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changeInEvent));
        
        string IMigrationMetadata.Id
        {
            get { return "201712131507578_changeInEvent"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
