// <auto-generated />
namespace Lexicon_LMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class startWorking1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(startWorking1));
        
        string IMigrationMetadata.Id
        {
            get { return "201712131530196_startWorking1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
